### PR TITLE
Update listener port for express app

### LINKED ISSUE #30: Service is not accessible when following Build and deploy to Azure Kubernetes Service with Azure Pipelines
Following the How To guide here: https://docs.microsoft.com/en-us/azure/aks/devops-pipeline?view=azure-devops&pivots=pipelines-yaml

The latest pull request #26 has changed the port that the express app listens on from 8080 to 3000, so when the Azure Pipeline creates the service in AKS the app is no longer accessible. The default service.yml file configures a service port but not a target port, so the default action is for the target port to be the same as the service port. This defaults to 80 when creating a pipeline from the template, but reading the How To guide, it is implied that this will be set to 8080, based on the instruction to 'Open a new browser tab or window and enter <IP address>:8080.'

### PR DESCRIPTION
**Pull request by p1johnson**
Resolves #30 which describes that following the How To guide [Build and deploy to Azure Kubernetes Service with Azure Pipelines](https://docs.microsoft.com/en-us/azure/aks/devops-pipeline?view=azure-devops&pivots=pipelines-yaml) will result in the application being unavailable via the service.

### CODE REVIEW

**Comment by p1johnson** [comment]
@juliakm could you have a look at this PR please, which ties in with the Docs PR from yesterday?

**Comment by AlinDanielFerenczi** [comment]
The docker file needs to expose port 8080 as well in order for this to work.

**Comment by p1johnson** [comment]
I found that the example worked without including EXPOSE 8080 in the Dockerfile. My understanding is that the EXPOSE instruction is for documentation purposes. [EXPOSE](https://docs.docker.com/engine/reference/builder/#expose)

**Comment by AlinDanielFerenczi** [comment]
I just made a test with this and it did not work until exposing the port. I think the instruction works as a firewall rule.

**Comment by p1johnson** [comment]
@AlinDanielFerenczi for the sake of completeness I've added the instruction EXPOSE 8080 to the Dockerfile.

**Comment by juliakm** [comment]
Thanks @p1johnson!

**Pull request merged**
